In [1]:
import numpy as np 
import pandas as pd
from pathlib import Path

In [6]:
xlsx_file = pd.read_excel("../data/raw/fuelcheck_pricehistory_dec2025.xlsx")
xlsx_file.head()

,ServiceStationName,Address,Suburb,Postcode,Brand,FuelCode,PriceUpdatedDate,Price
0,BP RANDWICK,"8-10 Perouse Road, RANDWICK NSW 2031",RANDWICK,2031,BP,P98,2025-12-01 01:27:10,199.9
1,Metro Petroleum South Hurstville,"928-930 KING GEORGES RD, BLAKEHURST NSW 2221",BLAKEHURST,2221,Metro Fuel,E10,2025-12-01 02:07:54,164.9
2,Metro Petroleum South Hurstville,"928-930 KING GEORGES RD, BLAKEHURST NSW 2221",BLAKEHURST,2221,Metro Fuel,U91,2025-12-01 02:07:54,166.9
3,Metro Petroleum South Hurstville,"928-930 KING GEORGES RD, BLAKEHURST NSW 2221",BLAKEHURST,2221,Metro Fuel,PDL,2025-12-01 02:07:54,174.9
4,ENHANCE TERALBA,"63 York St, Teralba NSW 2284",Teralba,2284,Enhance,U91,2025-12-01 04:16:26,179.9

In [8]:
csv_file = pd.read_csv("../data/raw/price_history_checks_oct2025.csv")
csv_file.head()

,ServiceStationName,Address,Suburb,Postcode,Brand,FuelCode,PriceUpdatedDate,Price
0,7-Eleven Fairfield,"320 Polding St, FAIRFIELD WEST NSW 2165",FAIRFIELD WEST,2165,7-Eleven,E10,1/10/2025 0:00,163.9
1,7-Eleven Fairfield,"320 Polding St, FAIRFIELD WEST NSW 2165",FAIRFIELD WEST,2165,7-Eleven,U91,1/10/2025 0:00,165.9
2,7-Eleven Fairfield,"320 Polding St, FAIRFIELD WEST NSW 2165",FAIRFIELD WEST,2165,7-Eleven,P95,1/10/2025 0:00,180.9
3,7-Eleven Fairfield,"320 Polding St, FAIRFIELD WEST NSW 2165",FAIRFIELD WEST,2165,7-Eleven,P98,1/10/2025 0:00,188.9
4,7-Eleven Berowra,"965-969 Pacific Highway (Corner Waratah Road),...",Berowra,2081,7-Eleven,P95,1/10/2025 0:00,181.9

In [ ]:
folder_path = Path("../data/raw")

merge_file = []

for file_path in sorted(folder_path.iterdir()):
    if file_path.suffix.lower() == ".csv":
        merge_file.append(pd.read_csv(file_path, dtype=str, keep_default_na=False, ignore_index=True).assign(source_file=file_path.name))
    elif file_path.suffix.lower() == ".xlsx":
        merge_file.append(pd.read_excel(file_path, dtype=str, keep_default_na=False, ignore_index=True).assign(source_file=file_path.name))

full_table = pd.concat(merge_file)
full_table.head()

,ServiceStationName,Address,Suburb,Postcode,Brand,FuelCode,PriceUpdatedDate,Price,source_file
0,Ampol Denham Court,"194 CAMPBELLTOWN RD, DENHAM COURT NSW 2565",DENHAM COURT,2565,Ampol,U91,2026-04-01 00:06:24,239.5,fuelcheck_pricehistory_apr2026.xlsx
1,Liberty Albert,"9, Melrose Road, Albert NSW 2873",Albert,2873,Liberty,U91,2026-04-01 00:22:59,274.9,fuelcheck_pricehistory_apr2026.xlsx
2,Liberty Bourke,"96-104 ANSON ST, BOURKE NSW 2840",BOURKE,2840,Liberty,U91,2026-04-01 00:23:27,264.9,fuelcheck_pricehistory_apr2026.xlsx
3,Liberty Bourke,"96-104 ANSON ST, BOURKE NSW 2840",BOURKE,2840,Liberty,P95,2026-04-01 00:23:27,274.9,fuelcheck_pricehistory_apr2026.xlsx
4,SHELL TAMWORTH TRUCKSTOP (unmanned),"9-13 Gunnedah Road, Tamworth NSW 2340",Tamworth,2340,Shell,DL,2026-04-01 00:23:53,299.9,fuelcheck_pricehistory_apr2026.xlsx

- 30.3s for loading 13 files
- full_table have 1258332 rows

In [ ]:
# Rows for each month
full_table.groupby("source_file").size()

source_file
fuelcheck_pricehistory_apr2026.xlsx     126651
fuelcheck_pricehistory_aug2025.xlsx      74898
fuelcheck_pricehistory_aug2026.xlsx     129143
fuelcheck_pricehistory_dec2025.xlsx      88277
fuelcheck_pricehistory_jan2026.xlsx      74525
fuelcheck_pricehistory_july2026.xlsx    155167
fuelcheck_pricehistory_jun2026.xlsx     103735
fuelcheck_pricehistory_may2026.xlsx      76567
fuelcheck_pricehistory_nov2025.xlsx      79181
fuelcheck_pricehistory_sep2025.xlsx      66938
price_history_checks_feb2026.csv         66981
price_history_checks_mar2026.csv        147137
price_history_checks_oct2025.csv         69132
dtype: int64

July 2026 is the largest and September 2025 is the smallest

In [ ]:
full_table.loc[full_table["source_file"] == "fuelcheck_pricehistory_july2026.xlsx"]

,ServiceStationName,Address,Suburb,Postcode,Brand,FuelCode,PriceUpdatedDate,Price,source_file
0,BP Mascot,"1077 Botany Road, Mascot NSW 2020",Mascot,2020,BP,P98,2026-07-01 00:01:54,168.9,fuelcheck_pricehistory_july2026.xlsx
1,BP Mascot,"1077 Botany Road, Mascot NSW 2020",Mascot,2020,BP,U91,2026-07-01 00:01:54,169.9,fuelcheck_pricehistory_july2026.xlsx
2,BP Mascot,"1077 Botany Road, Mascot NSW 2020",Mascot,2020,BP,PDL,2026-07-01 00:01:54,189.9,fuelcheck_pricehistory_july2026.xlsx
3,BP Mascot,"1077 Botany Road, Mascot NSW 2020",Mascot,2020,BP,P98,2026-07-01 00:02:14,189.9,fuelcheck_pricehistory_july2026.xlsx
4,Medco Kanahooka,"90-94 Lakeside Dr, KANAHOOKA NSW 2530",KANAHOOKA,2530,Independent,U91,2026-07-01 00:02:32,179.7,fuelcheck_pricehistory_july2026.xlsx
...,...,...,...,...,...,...,...,...,...
155162,7-Eleven Ryde,"326-328 Blaxland Road, Ryde NSW 2112",Ryde,2112,7-Eleven,E10,2026-07-31 23:24:14,191.9,fuelcheck_pricehistory_july2026.xlsx
155163,7-Eleven Ryde,"326-328 Blaxland Road, Ryde NSW 2112",Ryde,2112,7-Eleven,U91,2026-07-31 23:24:14,193.9,fuelcheck_pricehistory_july2026.xlsx
155164,Metro Petroleum Ingleburn,"21-23 CUMBERLAND RD, INGLEBURN NSW 2565",INGLEBURN,2565,Metro Fuel,E10,2026-07-31 23:24:54,189.5,fuelcheck_pricehistory_july2026.xlsx
155165,Bp woonona,"426 Princes Highway, WOONONA NSW 2517",WOONONA,2517,BP,U91,2026-07-31 23:56:07,195.9,fuelcheck_pricehistory_july2026.xlsx
155166,Bp woonona,"426 Princes Highway, WOONONA NSW 2517",WOONONA,2517,BP,P98,2026-07-31 23:56:07,222.9,fuelcheck_pricehistory_july2026.xlsx

In [ ]:
full_table.nunique()

ServiceStationName      2605
Address                 2519
Suburb                  1485
Postcode                 550
Brand                     66
FuelCode                   9
PriceUpdatedDate      289410
Price                   1675
source_file               13
dtype: int64